create table system_messages (
  id bigint generated by default as identity primary key,
  code varchar(80) not null unique,
  message varchar(500) not null,
  created_at timestamptz not null default current_timestamp
);

insert into system_messages (code, message)
values (
  'frontend-backend',
  'Kavya Portfolio frontend and Spring Boot API are ready to connect.'
);
