create table projects (
  id bigint generated by default as identity primary key,
  title varchar(160) not null,
  slug varchar(180) not null unique,
  description varchar(2000) not null,
  github_url varchar(500),
  live_url varchar(500),
  status varchar(30) not null,
  featured boolean not null default false,
  display_order integer not null default 0,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table project_technologies (
  project_id bigint not null references projects(id) on delete cascade,
  display_order integer not null,
  technology varchar(100) not null,
  primary key (project_id, display_order)
);

create table skills (
  id bigint generated by default as identity primary key,
  category varchar(100) not null,
  name varchar(120) not null,
  proficiency_level integer not null check (proficiency_level between 1 and 100),
  display_order integer not null default 0,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table education (
  id bigint generated by default as identity primary key,
  institution varchar(180) not null,
  degree varchar(180) not null,
  field_of_study varchar(180),
  start_date date not null,
  end_date date,
  description varchar(1500),
  display_order integer not null default 0,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint education_dates_valid check (end_date is null or end_date >= start_date)
);

create table certifications (
  id bigint generated by default as identity primary key,
  title varchar(180) not null,
  issuer varchar(180) not null,
  issue_date date,
  credential_id varchar(180),
  credential_url varchar(500),
  display_order integer not null default 0,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table experiences (
  id bigint generated by default as identity primary key,
  organization varchar(180) not null,
  role varchar(160) not null,
  location varchar(160),
  start_date date not null,
  end_date date,
  is_current boolean not null default false,
  description varchar(2000),
  display_order integer not null default 0,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint experience_dates_valid check (end_date is null or end_date >= start_date),
  constraint current_experience_has_no_end check (not is_current or end_date is null)
);

create table experience_highlights (
  experience_id bigint not null references experiences(id) on delete cascade,
  display_order integer not null,
  highlight varchar(500) not null,
  primary key (experience_id, display_order)
);

create table social_links (
  id bigint generated by default as identity primary key,
  platform varchar(80) not null,
  display_label varchar(120) not null,
  url varchar(500) not null,
  active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table resume_profiles (
  id bigint generated by default as identity primary key,
  full_name varchar(160) not null,
  headline varchar(200) not null,
  summary varchar(3000) not null,
  email varchar(254) not null,
  phone varchar(40),
  location varchar(160),
  resume_url varchar(500),
  photo_url varchar(500),
  active boolean not null default true,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table contact_messages (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  email varchar(254) not null,
  subject varchar(200) not null,
  message varchar(5000) not null,
  is_read boolean not null default false,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create index idx_projects_display_order on projects(display_order, id);
create index idx_skills_display_order on skills(display_order, id);
create index idx_experiences_display_order on experiences(display_order, id);
create index idx_contact_messages_created_at on contact_messages(created_at desc);

insert into projects
  (title, slug, description, github_url, status, featured, display_order)
values
  ('Developer Portfolio System', 'developer-portfolio-system',
   'A responsive portfolio with reusable content sections, motion, themes, and a scalable API foundation.',
   'https://github.com/chaurasiyaji02/kavya-portfolio', 'IN_PROGRESS', true, 1),
  ('Private Resume Toolkit', 'private-resume-toolkit',
   'A browser-only resume builder and checker with reusable previews, ATS guidance, and local storage.',
   'https://github.com/chaurasiyaji02/kavya-portfolio', 'COMPLETED', true, 2);

insert into project_technologies (project_id, display_order, technology)
select id, 0, 'React' from projects where slug = 'developer-portfolio-system';
insert into project_technologies (project_id, display_order, technology)
select id, 1, 'Spring Boot' from projects where slug = 'developer-portfolio-system';
insert into project_technologies (project_id, display_order, technology)
select id, 2, 'PostgreSQL' from projects where slug = 'developer-portfolio-system';
insert into project_technologies (project_id, display_order, technology)
select id, 0, 'React' from projects where slug = 'private-resume-toolkit';
insert into project_technologies (project_id, display_order, technology)
select id, 1, 'LocalStorage' from projects where slug = 'private-resume-toolkit';

insert into skills (category, name, proficiency_level, display_order) values
  ('Frontend', 'React', 80, 1),
  ('Frontend', 'JavaScript', 78, 2),
  ('Frontend', 'Tailwind CSS', 82, 3),
  ('Backend', 'Java', 72, 4),
  ('Backend', 'Spring Boot', 65, 5),
  ('Database', 'PostgreSQL', 62, 6),
  ('Tools', 'Git', 78, 7);

insert into education
  (institution, degree, field_of_study, start_date, end_date, description, display_order)
values
  ('University Name', 'Bachelor of Technology', 'Computer Science', '2022-08-01', '2026-06-30',
   'Coursework in data structures, web development, databases, and software engineering.', 1);

insert into certifications
  (title, issuer, issue_date, credential_url, display_order)
values
  ('Full-Stack Web Development', 'Online Learning Platform', '2025-03-01',
   'https://example.com/credentials/full-stack', 1),
  ('Java and Data Structures', 'Technical Training Program', '2024-08-01',
   'https://example.com/credentials/java', 2);

insert into experiences
  (organization, role, location, start_date, end_date, is_current, description, display_order)
values
  ('Technology Studio', 'Full-Stack Developer Intern', 'Remote', '2025-01-01', '2025-06-30', false,
   'Contributed to responsive frontend components, API integration, fixes, and technical documentation.', 1);

insert into experience_highlights (experience_id, display_order, highlight)
select id, 0, 'Built reusable React components' from experiences where role = 'Full-Stack Developer Intern';
insert into experience_highlights (experience_id, display_order, highlight)
select id, 1, 'Integrated REST API states' from experiences where role = 'Full-Stack Developer Intern';

insert into social_links (platform, display_label, url, active, display_order) values
  ('GitHub', 'GitHub', 'https://github.com/chaurasiyaji02', true, 1),
  ('LinkedIn', 'LinkedIn', 'https://www.linkedin.com', true, 2);

insert into resume_profiles
  (full_name, headline, summary, email, phone, location, resume_url, active)
values
  ('Kavya Chaurasiya', 'Java and Full-Stack Developer',
   'Computer science student building responsive React interfaces and dependable Java foundations.',
   'kavya@example.com', '+91 00000 00000', 'India', '/resume', true);
