create table admin_users (
  id bigint generated by default as identity primary key,
  email varchar(254) not null unique,
  password_hash varchar(100) not null,
  role varchar(40) not null,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create unique index idx_admin_users_email_lower on admin_users(lower(email));
