const text = (name, label, options = {}) => ({ name, label, type: 'text', ...options });
const url = (name, label, options = {}) => ({ name, label, type: 'url', ...options });
const date = (name, label, options = {}) => ({ name, label, type: 'date', ...options });
const number = (name, label, options = {}) => ({ name, label, type: 'number', ...options });
const checkbox = (name, label) => ({ name, label, type: 'checkbox' });
const textarea = (name, label, options = {}) => ({ name, label, type: 'textarea', ...options });
const list = (name, label, options = {}) => ({ name, label, type: 'list', ...options });

export const adminResources = [
  {
    key: 'projects',
    label: 'Projects',
    singular: 'Project',
    reorderable: true,
    defaults: {
      title: '',
      slug: '',
      description: '',
      githubUrl: '',
      liveUrl: '',
      imageUrl: '',
      status: 'IN_PROGRESS',
      featured: false,
      displayOrder: 0,
      technologies: [],
    },
    fields: [
      text('title', 'Title', { required: true, maxLength: 160 }),
      text('slug', 'Slug', {
        required: true,
        maxLength: 180,
        pattern: '[a-z0-9]+(?:-[a-z0-9]+)*',
        hint: 'Lowercase words separated by hyphens.',
      }),
      textarea('description', 'Description', { required: true, maxLength: 2000, wide: true }),
      url('githubUrl', 'GitHub URL', { maxLength: 500 }),
      url('liveUrl', 'Live demo URL', { maxLength: 500 }),
      url('imageUrl', 'Project image URL', { maxLength: 500, wide: true }),
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          ['IN_PROGRESS', 'In progress'],
          ['COMPLETED', 'Completed'],
          ['PLANNED', 'Planned'],
        ],
      },
      number('displayOrder', 'Display order', { required: true, min: 0 }),
      list('technologies', 'Technologies', {
        required: true,
        maxItems: 20,
        hint: 'One technology per line.',
        wide: true,
      }),
      checkbox('featured', 'Featured project'),
    ],
    title: (item) => item.title,
    meta: (item) => `${item.status.replaceAll('_', ' ')} · ${item.technologies.join(', ')}`,
  },
  {
    key: 'skills',
    label: 'Skills',
    singular: 'Skill',
    reorderable: true,
    defaults: { category: '', name: '', proficiencyLevel: 70, displayOrder: 0 },
    fields: [
      text('category', 'Category', { required: true, maxLength: 100 }),
      text('name', 'Skill name', { required: true, maxLength: 120 }),
      number('proficiencyLevel', 'Proficiency', { required: true, min: 1, max: 100 }),
      number('displayOrder', 'Display order', { required: true, min: 0 }),
    ],
    title: (item) => item.name,
    meta: (item) => `${item.category} · ${item.proficiencyLevel}%`,
  },
  {
    key: 'education',
    label: 'Education',
    singular: 'Education',
    reorderable: true,
    defaults: {
      institution: '',
      degree: '',
      fieldOfStudy: '',
      startDate: '',
      endDate: '',
      description: '',
      displayOrder: 0,
    },
    fields: [
      text('institution', 'Institution', { required: true, maxLength: 180 }),
      text('degree', 'Degree', { required: true, maxLength: 180 }),
      text('fieldOfStudy', 'Field of study', { maxLength: 180 }),
      date('startDate', 'Start date', { required: true }),
      date('endDate', 'End date'),
      number('displayOrder', 'Display order', { required: true, min: 0 }),
      textarea('description', 'Description', { maxLength: 1500, wide: true }),
    ],
    title: (item) => item.degree,
    meta: (item) => `${item.institution} · ${item.startDate} to ${item.endDate || 'Present'}`,
  },
  {
    key: 'certifications',
    label: 'Certifications',
    singular: 'Certification',
    reorderable: true,
    defaults: {
      title: '',
      issuer: '',
      issueDate: '',
      credentialId: '',
      credentialUrl: '',
      displayOrder: 0,
    },
    fields: [
      text('title', 'Title', { required: true, maxLength: 180 }),
      text('issuer', 'Issuer', { required: true, maxLength: 180 }),
      date('issueDate', 'Issue date'),
      text('credentialId', 'Credential ID', { maxLength: 180 }),
      url('credentialUrl', 'Credential URL', { maxLength: 500, wide: true }),
      number('displayOrder', 'Display order', { required: true, min: 0 }),
    ],
    title: (item) => item.title,
    meta: (item) => `${item.issuer}${item.issueDate ? ` · ${item.issueDate}` : ''}`,
  },
  {
    key: 'experiences',
    label: 'Experience',
    singular: 'Experience',
    reorderable: true,
    defaults: {
      organization: '',
      role: '',
      location: '',
      startDate: '',
      endDate: '',
      currentRole: false,
      description: '',
      displayOrder: 0,
      highlights: [],
    },
    fields: [
      text('organization', 'Organization', { required: true, maxLength: 180 }),
      text('role', 'Role', { required: true, maxLength: 160 }),
      text('location', 'Location', { maxLength: 160 }),
      date('startDate', 'Start date', { required: true }),
      date('endDate', 'End date'),
      number('displayOrder', 'Display order', { required: true, min: 0 }),
      textarea('description', 'Description', { maxLength: 2000, wide: true }),
      list('highlights', 'Highlights', {
        maxItems: 20,
        hint: 'One achievement per line.',
        wide: true,
      }),
      checkbox('currentRole', 'This is my current role'),
    ],
    title: (item) => item.role,
    meta: (item) => `${item.organization} · ${item.startDate} to ${item.currentRole ? 'Present' : item.endDate || 'Present'}`,
  },
  {
    key: 'social-links',
    label: 'Social Links',
    singular: 'Social link',
    reorderable: true,
    defaults: { platform: '', displayLabel: '', url: '', active: true, displayOrder: 0 },
    fields: [
      text('platform', 'Platform', { required: true, maxLength: 80 }),
      text('displayLabel', 'Display label', { required: true, maxLength: 120 }),
      url('url', 'Profile URL', { required: true, maxLength: 500, wide: true }),
      number('displayOrder', 'Display order', { required: true, min: 0 }),
      checkbox('active', 'Show publicly'),
    ],
    title: (item) => item.displayLabel,
    meta: (item) => `${item.platform} · ${item.active ? 'Public' : 'Hidden'}`,
  },
  {
    key: 'resume-profiles',
    label: 'Resume Profile',
    singular: 'Resume profile',
    reorderable: false,
    defaults: {
      fullName: '',
      headline: '',
      summary: '',
      email: '',
      phone: '',
      location: '',
      resumeUrl: '',
      photoUrl: '',
      active: true,
    },
    fields: [
      text('fullName', 'Full name', { required: true, maxLength: 160 }),
      text('headline', 'Professional headline', { required: true, maxLength: 200 }),
      { name: 'email', label: 'Email', type: 'email', required: true, maxLength: 254 },
      text('phone', 'Phone', { maxLength: 40 }),
      text('location', 'Location', { maxLength: 160 }),
      textarea('summary', 'Professional summary', { required: true, maxLength: 3000, wide: true }),
      url('resumeUrl', 'Resume link', { maxLength: 500, wide: true }),
      url('photoUrl', 'Resume photo URL', { maxLength: 500, wide: true }),
      checkbox('active', 'Use as active public profile'),
    ],
    title: (item) => item.fullName,
    meta: (item) => `${item.headline} · ${item.active ? 'Active' : 'Inactive'}`,
  },
];

export const contactResource = {
  key: 'contact-messages',
  label: 'Contact Messages',
};
